[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "["
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "]"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "1"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "2"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "3"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "4"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "5"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "6"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "7"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "8"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "9"
mods = "Command"
action = "None"
