# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
# Setup Rust Path
export CARGO_HOME=$HOME/.cargo
export PATH=$CARGO_HOME/bin:$PATH

# Setup PNPM Path
export PNPM_HOME=$HOME/.local/share/pnpm
export PATH=$PNPM_HOME:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="robbyrussell"
export STARSHIP_CONFIG=~/.config/starship/config.toml

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Configure Plugins
# eza
EZA_TIME_STYLE="%Y%m%d %H%M
 %m-%d %H:%M "
if (( $+commands[eza] )); then
  zstyle ':omz:plugins:eza' 'icons' yes
  zstyle ':omz:plugins:eza' 'time-style' "+$EZA_TIME_STYLE"
  alias tree="l --tree"
fi

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  aws
  docker
  docker-compose
  dotenv
  eza
  fzf
  gh
  git
  git-lfs
  golang
  gpg-agent
  macos
  mise
  python
  rust
  starship
  uv
  zoxide
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='hx'
else
  export EDITOR='hx'
fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias vim='nvim --clean'
alias zrf='zellij run --floating'
alias export_esprs_env='source $HOME/export-esp.sh'

# GnuPG for SSH Agent Setup (Setup by oh-my-zsh plugin gpg-agent)
# export GPG_TTY="$(tty)"
# export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
# gpgconf --launch gpg-agent

# Starship Prompt Setup (Setup by oh-my-zsh plugin starship)
# export STARSHIP_CONFIG=~/.config/starship/config.toml
# eval "$(starship init zsh)"

# Mise Setup (Setup by oh-my-zsh plugin mise)
# eval "$(~/.local/bin/mise activate zsh)"

# Skim Setup
SKIM_BASE="" # empty to auto determine
DISABLE_SKIM_AUTO_COMPLETION="true"
DISABLE_SKIM_KEY_BINDINGS="true"
function skim_setup() {
  local skim_base skim_shell skim_dirs
   
  test -d "${SKIM_BASE}" && skim_base="${SKIM_BASE}"

  if [[ -z "${skim_base}" ]]; then
    skim_dirs=(
      "${HOME}/.sk"
      "${HOME}/.nix-profile/share/sk"
      "${XDG_DATA_HOME:-$HOME/.local/share}/sk"
      "${MSYSTEM_PREFIX}/share/sk"
      "/usr/local/opt/sk"
      "/opt/homebrew/opt/sk"
      "/usr/share/sk"
      "/usr/local/share/examples/sk"
    )
    for dir in ${skim_dirs}; do
      if [[ -d "${dir}" ]]; then
        skim_base="${dir}"
        break
      fi
    done

    if [[ -z "${skim_base}" ]]; then
      if (( $+commands[brew] )) && dir="$(brew --prefix sk 2>/dev/null)"; then
        if [[ -d "${dir}" ]]; then
          skim_base="${dir}"
        fi
      fi
    fi

    if [[ ! -d "${skim_base}" ]]; then
      return 1
    fi

    # Setup skim binary path
    if (( ! $+commands[sk] )) && [[ "$PATH" != *$skim_base/bin* ]]; then
      export PATH="$PATH:$skim_base/bin"
    fi

    # Auto-completion
    if [[ -o interactive && "$DISABLE_SKIM_AUTO_COMPLETION" != "true" ]]; then
      eval "$(sk --shell zsh)"
    fi

    # Key bindings
    skim_shell="${skim_base}/share/zsh/site-functions"
    if [[ "$DISABLE_SKIM_KEY_BINDINGS" != "true" ]]; then
      source "${skim_shell}/key-bindings.zsh"
    fi

  fi
}

function skim_setup_error() {
  cat >&2 <<'EOF'
[oh-my-zsh] skim setup: Cannot find skim installation directory.
Please add `export SKIM_BASE=/path/to/skim/install/dir` to your .zshrc
EOF
}

skim_setup || skim_setup_error
unset -f -m 'skim_setup*'
unset SKIM_BASE DISABLE_SKIM_AUTO_COMPLETION DISABLE_SKIM_KEY_BINDINGS

# Zellij Setup when Alacritty
if [ "$TERM" = "alacritty" ] && [ "$ZED_TERM" != "true" ]; then
  export EDITOR='hx'
  ZELLIJ_AUTO_ATTACH=true
  ZELLIJ_AUTO_EXIT=true
  eval "$(zellij setup --generate-auto-start zsh)"
fi

